set -gF @tmux_sidebar_dir "#{d:current_file}"

if-shell -F '#{==:#{@tmux_sidebar_install_agent_hooks},1}' "run-shell -b '#{@tmux_sidebar_dir}/scripts/features/hooks/install-agent-hooks.sh'"
run-shell -b "#{@tmux_sidebar_dir}/scripts/features/sidebar/configure-pane-border-format.sh"
bind-key t run-shell -b "#{@tmux_sidebar_dir}/scripts/features/sidebar/toggle-sidebar.sh"
bind-key T run-shell -b "#{@tmux_sidebar_dir}/scripts/features/sidebar/focus-sidebar.sh"
set-hook -g "client-active[198]" "run-shell -b '#{@tmux_sidebar_dir}/scripts/features/sidebar/ensure-sidebar-pane.sh'"
set-hook -g "client-attached[199]" "run-shell -b '#{@tmux_sidebar_dir}/scripts/features/sidebar/ensure-sidebar-pane.sh'"
set-hook -g "client-session-changed[200]" "run-shell -b '#{@tmux_sidebar_dir}/scripts/features/sidebar/on-pane-focus.sh #{pane_id} #{window_id}'"
set-hook -g "client-focus-in[202]" "run-shell -b '#{@tmux_sidebar_dir}/scripts/features/sidebar/on-pane-focus.sh #{pane_id} #{window_id}'"
set-hook -g "after-select-window[203]" "run-shell -b '#{@tmux_sidebar_dir}/scripts/features/sidebar/on-pane-focus.sh #{pane_id} #{window_id}'"
set-hook -g "after-select-pane[204]" "run-shell -b '#{@tmux_sidebar_dir}/scripts/features/sidebar/on-pane-focus.sh #{pane_id} #{window_id}'"
set-hook -g "session-window-changed[205]" "run-shell -b '#{@tmux_sidebar_dir}/scripts/features/sidebar/on-pane-focus.sh #{pane_id} #{window_id}'"
set-hook -g "after-split-window[206]" "run-shell -b '#{@tmux_sidebar_dir}/scripts/features/sidebar/notify-sidebar.sh'"
set-hook -g "after-new-window[207]" "run-shell -b '#{@tmux_sidebar_dir}/scripts/features/sidebar/ensure-sidebar-pane.sh #{hook_pane} #{hook_window}'"
set-hook -g "after-kill-pane[208]" "run-shell -b '#{@tmux_sidebar_dir}/scripts/features/sidebar/handle-pane-exited.sh #{hook_pane} #{hook_window}'"
set-hook -g "after-resize-pane[209]" "run-shell -b '#{@tmux_sidebar_dir}/scripts/features/sidebar/notify-sidebar.sh'"
set-hook -g "after-rename-window[210]" "run-shell -b '#{@tmux_sidebar_dir}/scripts/features/sidebar/notify-sidebar.sh'"
set-hook -g "after-rename-session[211]" "run-shell -b '#{@tmux_sidebar_dir}/scripts/features/sidebar/notify-sidebar.sh'"
run-shell -b "#{@tmux_sidebar_dir}/scripts/features/sidebar/apply-key-overrides.sh"
run-shell -b "bash #{@tmux_sidebar_dir}/scripts/features/context-menu/bind-context-menu.sh"
