from __future__ import annotations

DEFAULT_BADGES: dict[str, str] = {
    "running": "⏳",
    "needs-input": "❓",
    "done": "✅",
    "error": "❌",
}
NERD_FONT_BADGES: dict[str, str] = {
    "running": "\uf252",
    "needs-input": "\uf059",
    "done": "\uf05d",
    "error": "\uf46e",
}

ASCII_ICONS: dict[str, str] = {
    "claude": "C",
    "codex": "X",
    "opencode": "O",
    "cursor": "U",
    "shell": "$",
    "node": "N",
    "python": "P",
    "git": "G",
    "lazygit": "G",
    "yazi": "Y",
    "ranger": "R",
    "bb": "B",
    "cat": "c",
    "clojure": "L",
    "java": "J",
    "less": ":",
    "vim": "V",
    "ssh": "@",
    "pager": ":",
    "top": "%",
    "tmux": "T",
    "unknown": "?",
}
UNICODE_ICONS: dict[str, str] = {
    "claude": "◎",
    "codex": "⌘",
    "opencode": "◌",
    "cursor": "▣",
    "shell": "›",
    "node": "⬢",
    "python": "¶",
    "git": "⎇",
    "lazygit": "⎇",
    "yazi": "▤",
    "ranger": "▥",
    "bb": "β",
    "cat": "⌂",
    "clojure": "λ",
    "java": "♨",
    "less": "↕",
    "vim": "◇",
    "ssh": "↗",
    "pager": "↕",
    "top": "▦",
    "tmux": "⊞",
    "unknown": "·",
}
NERD_FONT_ICONS: dict[str, str] = {
    "claude": "\U000f0d70",
    "codex": "\U000f0d70",
    "opencode": "\U000f0d70",
    "cursor": "\U000f0d70",
    "shell": "\U000f016c",
    "node": "\ue719",
    "python": "\ue73c",
    "git": "\ue702",
    "lazygit": "\U000f02a2",
    "yazi": "\U000f024b",
    "ranger": "\ueb86",
    "bb": "\ue768",
    "cat": "\U000f011b",
    "clojure": "\ue768",
    "java": "\ue738",
    "less": "\ue758",
    "vim": "\ue7c5",
    "ssh": "\ue8b1",
    "pager": "\ueb2f",
    "top": "\U000f1513",
    "tmux": "\uebc8",
    "unknown": "\ueb32",
}
ICON_THEMES: dict[str, dict[str, str]] = {
    "ascii": ASCII_ICONS,
    "nerdfont": NERD_FONT_ICONS,
    "unicode": UNICODE_ICONS,
}
APP_ALIASES: dict[str, str] = {
    "ash": "shell",
    "bash": "shell",
    "dash": "shell",
    "elvish": "shell",
    "fish": "shell",
    "ksh": "shell",
    "nu": "shell",
    "sh": "shell",
    "xonsh": "shell",
    "zsh": "shell",
    "node": "node",
    "nodejs": "node",
    "python": "python",
    "python2": "python",
    "python3": "python",
    "git": "git",
    "lazygit": "lazygit",
    "yazi": "yazi",
    "ranger": "ranger",
    "bb": "bb",
    "babashka": "bb",
    "cat": "cat",
    "clj": "clojure",
    "clojure": "clojure",
    "java": "java",
    "less": "less",
    "vi": "vim",
    "vim": "vim",
    "nvim": "vim",
    "view": "vim",
    "ssh": "ssh",
    "mosh": "ssh",
    "mosh-client": "ssh",
    "more": "pager",
    "most": "pager",
    "tail": "pager",
    "atop": "top",
    "bpytop": "top",
    "btop": "top",
    "htop": "top",
    "top": "top",
    "tmux": "tmux",
}
ICON_THEME_OPTION = "@tmux_sidebar_icon_theme"
FONT_DIRS_ENV = "TMUX_SIDEBAR_FONT_DIRS"
FONT_FILE_SUFFIXES = {".otf", ".otc", ".ttc", ".ttf"}
